### ISSUE TITLE
install SwiftMock by CocoaPods?

### ISSUE THREAD

**Issue by ShenYj** [mflint/SwiftMock#10]
-> SwiftMock (0.0.3) [DEPRECATED]
   A mocking framework for Swift 2.0
   pod 'SwiftMock', '~> 0.0.3'
   - Homepage: https://github.com/mflint/SwiftMock
   - Source:   https://github.com/mflint/SwiftMock.git
   - Versions: 0.0.3, 0.0.2, 0.0.1 [cocoapods repo]

**Comment by mflint** [comment]
CocoaPods will probably never be supported - but I would like to support Swift Package Manager.

The code is all in one file, so you could copy it into your project.
