### ISSUE TITLE
How to set multiple expectation

### ISSUE THREAD

**Issue by RohitNegi** [mflint/SwiftMock#12]
How to set multiple expectations in a single test method.

**Comment by mflint** [comment]
There’s nothing stopping you from doing this, @RohitNegi, but the mock does _not_ check the order in which expected calls are received.

```
firstMock.expect { $0.something() }
firstMock.expect { $0.somethingElse() }
secondMock.expect { $0.anotherFunction() }

…
firstMock.verify()
secondMock.verify()
```

Are you seeing a problem when trying to do this?

**Comment by RohitNegi** [comment]
This is the method for which I am writing test case.
func getYearsFilter() {
        showLoadingSpinner()
        self.filters = statementRepo.getMfStatementFilter()
        if self.filters.count == 0 {
            self.statementRepo.getYearsFilter(
                success: {
                    response in
                    if self.statementRepo.getMfStatementFilter().count == 0 {
                        self.createYearlyMfStatementFilters()
                        self.statementRepo.setYearSelected(year: self.filters[self.defaultSelectedFilter].filterName ?? "")
                    }
                    self.getMfStatementFilters()
                    hideLoadingSpinner()
                },
                failure: {
                    error in
                    hideLoadingSpinner()
                    if let exception = error as? Exception{
                        show(exception: exception)
                    }
                })
        } else {
            hideLoadingSpinner()
        }
    }


My UT is like below. It is crashing on test_getYearsFilter_if() as we are setting up expectations order like below. 
class SelectUHNViewModelTest {
    private let selectUHNViewModel = SelectUHNViewModel()
    private let mockMFStatementRepo = MockMFStatementRepo.create()
    
    override func setUp() {
        super.setUp()
		selectUHNViewModel.mfStatementRepo = mockMFStatementRepo
    }

    func test_getYearsFilter_if() {
        //given
        let  mfStatementFilterModel =  [MfStatementFilterModel]()
        var capturedCompletionBlock: ((YearsFilterResponse) -> Void)?
        let yearsFilterResponseObject = YearsFilterResponse()
        yearsFilterResponseObject.years = ["2020", "2019", "2018"]
        // expect a call on a function which returns a String value
        mockMFStatementRepo.expect { o in
            o.getMfStatementFilter()
        }.returning(mfStatementFilterModel)
        
        //expect
        mockMFStatementRepo.expect { m in
            m.getYearsFilter { (_) in } failure: { (_) in }
        }.doing { (actionArgs) in
            capturedCompletionBlock = actionArgs[0] as? ((YearsFilterResponse) -> Void)
        }
        
        //when
        selectUHNViewModel.getYearsFilter()
        //then
        mockMFStatementRepo.verify()
        capturedCompletionBlock?(yearsFilterResponseObject)
      //Assert
        XCTAssertEqual(selectUHNViewModel.yearsFilterOptions, yearsFilterResponseObject.years)
    }
}

class MockMFStatementRepo: Mock<MFStatementRepoProtocol>, MFStatementRepoProtocol {
	func getMfStatementFilter() -> [MfStatementFilterModel] {
       return accept() as! [MfStatementFilterModel]
    }
    func getYearsFilter(success: @escaping (YearsFilterResponse) -> Void, failure: @escaping (Exception) -> Void) {
        accept(checkArgs: [], actionArgs: [success, failure])
    }
    func setYearSelected(year: String) {
        accept(args: [year])
    }
    func getYearSelected() -> String {
        accept() as! String
    }   
}

**Comment by RohitNegi** [comment]
Order matters because it is working in reverse order. But if any expectation has doing block then doing block is not getting called. We can reverse the expectation order of the test method mentioned above and check. It does show any error but doing block is not getting called.

**Comment by mflint** [comment]
@RohitNegi I pushed a new version to a new branch, [`expectation-crash-fix`](https://github.com/mflint/SwiftMock/tree/expectation-crash-fix).

[Can you try this version of `Mock.swift`](https://raw.githubusercontent.com/mflint/SwiftMock/expectation-crash-fix/Mock.swift), please, to see if it helps you?

**Comment by raj-engineer** [comment]
thanks @mflint  , but one isssue i am facing,  if same function is calling twice. then its crashes. how to set expectation for that.  
firstMock.expect { $0.something() }
firstMock.expect { $0.something() }

**Comment by raj-engineer** [comment]
> @RohitNegi I pushed a new version to a new branch, [`expectation-crash-fix`](https://github.com/mflint/SwiftMock/tree/expectation-crash-fix).
> 
> [Can you try this version of `Mock.swift`](https://raw.githubusercontent.com/mflint/SwiftMock/expectation-crash-fix/Mock.swift), please, to see if it helps you?

thanks i tried the update mock file , it resolve the issue.

**Comment by raj-engineer** [comment]
thanks @mflint  , but one isssue i am facing,  if same function is calling twice. then its crashes. how to set expectation for that.  
```
firstMock.expect { $0.something() }
firstMock.expect { $0.something() }
```

**Comment by raj-engineer** [comment]
> thanks @mflint , but one isssue i am facing, if same function is calling twice. then its crashes. how to set expectation for that.
> 
> ```
> firstMock.expect { $0.something() }
> firstMock.expect { $0.something() }
> ```

the issue is resolved , i just called verify function after capturedCompletionBlock?(response).

**Comment by mflint** [comment]
Can this issue be closed, @RohitNegi / @raj-engineer ?

**Comment by raj-engineer** [comment]
yes @mflint

**Comment by mflint** [comment]
One more thing, @raj-engineer:

I can't think of any reason why you'd want to set the same expectation twice. 🤔 

Is that function a command - the mock is being told to do perform some operation - or is it simply a request for information? If it's a request for information, then maybe you don't want to mock that function.

(I wrote some information in the README about mocking and stubbing)
