### ISSUE TITLE
doing block is not working in multiple expectation

### ISSUE THREAD

**Issue by RohitNegi** [mflint/SwiftMock#13]
`func test_getYearsFilter_if() {

        //given
        var capturedCompletionBlock: ((YearsFilterResponse) -> Void)?
        let yearsFilterResponseObject = YearsFilterResponse()
        yearsFilterResponseObject.years = ["2020", "2019", "2018"]
        let  statementFilterModel =  [StatementFilterModel]()
        //expect

        mockMFStatementRepo.expect { m in
            m.getYearsFilter { (_) in } failure: { (_) in }
        }.doing { (actionArgs) in
            capturedCompletionBlock = actionArgs[0] as? ((YearsFilterResponse) -> Void)
        }
        // expect
        mockMFStatementRepo.expect { o in
            o.getMfStatementFilter()
        }.returning(statementFilterModel)

        //when
        viewModel.getYearsFilter()
        //then
        mockMFStatementRepo.verify()
        // then later, call that captured block to simulate an incoming response
        capturedCompletionBlock?(yearsFilterResponseObject)

        //Assert
        XCTAssertEqual(viewModel.yearsFilterOptions, yearsFilterResponseObject.years)

    }`

**Comment by mflint** [comment]
Thank-you for raising an issue @RohitNegi, but I'll need more information to understand the problem.

Can you explain please:

* what you expect to happen
* what actually happens

**Comment by mflint** [comment]
Oh, I think I understand. This seems to be related to #12.

Investigating!

**Comment by mflint** [comment]
Can this issue be closed @RohitNegi ?

**Comment by RohitNegi** [comment]
Yes, it can be, thanks @mflint
