### ISSUE TITLE
If two methods have same signature, it fails

### ISSUE THREAD

**Issue by RohitNegi** [mflint/SwiftMock#17]
If two methods have same signature but different method name, it is failing because it try to match with method mentioned top in the hierarchy.
<img width="1680" alt="Screenshot 2021-07-27 at 6 13 59 PM" src="https://user-images.githubusercontent.com/3912483/127157141-c1e3988e-1155-49df-bf60-87684ea07724.png">

for example 
```
    func test_void_function() {
        //given
        viewModel = FroodViewModel(delegate: mockFrood)
        //expect
        mockFrood.expect { (f) in
            f.voidFunction(value: 11)
        }
        //when
        viewModel.checkVoidFunction(val: 11)
        //then
        verify()
    }
    
    func test_void_function1() {
        //given
        viewModel = FroodViewModel(delegate: mockFrood)
        //expect
        mockFrood.expect { (f) in
            f.voidFunction1(value: 11)
        }
        //when
        viewModel.checkVoidFunction(val: 11)
        //then
        verify()
    }
```

**Comment by mflint** [comment]
Can you post the code for your Mock object please?

Please also give more details about how "it fails"? What is the failure, and what did you expect to happen?

**Comment by RohitNegi** [comment]
my bad, setting up of expectation was incorrect that's why it was failing.  It should have been like viewModel.checkVoidFunction1(val: 11). 
thanks for reply.
